name: Publish PKGBUILD to AUR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: Validate tag format
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "❌ Invalid tag format. Expected: v1.2.3 or v1.2.3.4, got: $GITHUB_REF_NAME"
            exit 1
          fi
          echo "✅ Tag format is valid: $GITHUB_REF_NAME"

      - name: Update PKGBUILD version for tags
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          echo "🏷️ Updating to version: $TAG_VERSION"
          if [[ ! "$TAG_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "❌ Invalid version format: $TAG_VERSION"
            exit 1
          fi
          cp aur/PKGBUILD aur/PKGBUILD.backup
          sed -i "s/pkgver=.*/pkgver='$TAG_VERSION'/" aur/PKGBUILD
          sed -i "s/pkgrel=.*/pkgrel=1/" aur/PKGBUILD
          echo "✅ Updated PKGBUILD version to $TAG_VERSION"

      - name: Show PKGBUILD changes
        run: |
          echo "📝 PKGBUILD changes:"
          if [[ -f aur/PKGBUILD.backup ]]; then
            diff -u aur/PKGBUILD.backup aur/PKGBUILD || true
          fi
          echo ""
          echo "📋 Current PKGBUILD content:"
          cat aur/PKGBUILD

      - name: Prepare package files
        run: |
          echo "::group::Checking required files for AUR publication"
          for file in "aur/PKGBUILD"; do
            if [ ! -f "$file" ]; then
              echo "::error::Missing required file: $file"
              exit 1
            fi
          done
          echo "All required files present"
          echo "::endgroup::"

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: binary-package
          path: ./aur/

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: perplexity
          pkgbuild: aur/PKGBUILD
          assets: |
            aur/launcher.sh
            aur/perplexity.desktop
            aur/perplexity.png
            aur/default.conf
          updpkgsums: true
          test: true
          test_flags: '--clean --cleanbuild --syncdeps --noconfirm'
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          allow_empty_commits: false
          ssh_keyscan_types: rsa,ecdsa,ed25519

      - name: Publication Summary
        run: |
          echo "::group::AUR Publication Summary"
          echo "Package successfully published to AUR"
          echo "Version: ${{ github.ref_name }}"
          echo "All tests passed and package validated"
          echo "::endgroup::"

      - name: Success notification
        if: success()
        run: |
          echo "🎉 Successfully published ${{ github.ref_name }} to AUR!"
          echo "📦 Package: perplexity"
          echo "🔗 AUR URL: https://aur.archlinux.org/packages/perplexity"
          echo "⏰ Published at: $(date)"

      - name: Cleanup
        if: always()
        run: |
          rm -f aur/PKGBUILD.backup